# Generated by Django 5.0.2 on 2024-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTP3', '0002_curso_entregable_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_daño', models.CharField(max_length=60)),
                ('Total_daño', models.IntegerField()),
            ],
        ),
    ]
