# Generated by Django 5.0.2 on 2024-03-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTP3', '0003_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=60)),
                ('averno', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
