# Generated by Django 5.0.2 on 2024-03-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTP3', '0004_personajes_delete_entregable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajes',
            name='averno',
            field=models.CharField(max_length=60),
        ),
    ]
