# Generated by Django 5.0.2 on 2024-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTP3', '0005_alter_personajes_averno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armaduras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_armadura', models.CharField(max_length=30)),
                ('tipo_armadura', models.CharField(max_length=30)),
                ('lv_armadura', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
